# Generated by Django 5.2.12 on 2026-03-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Device name/label', max_length=100)),
                ('ip_address', models.CharField(help_text='Device IP address', max_length=50, unique=True)),
                ('port', models.IntegerField(default=4370, help_text='Device port (default: 4370)')),
                ('password', models.IntegerField(blank=True, default=0, help_text='Device password (default: 0)', null=True)),
                ('location', models.CharField(blank=True, help_text='Physical location of device', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=20, null=True)),
                ('connection_timeout', models.IntegerField(default=5, help_text='Connection timeout in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 'devices',
                'ordering': ['name'],
            },
        ),
    ]
