# Generated by Django 5.2.12 on 2026-03-29 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uid', models.IntegerField(help_text='User ID on this specific device')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_employees', to='devices.device')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_devices', to='core.employee')),
            ],
            options={
                'verbose_name': 'Employee Device',
                'verbose_name_plural': 'Employee Devices',
                'db_table': 'employee_devices',
                'unique_together': {('employee', 'device', 'device_uid')},
            },
        ),
    ]
