# Generated by Django 5.2.12 on 2026-03-29 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('devices', '0002_employeedevice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeedevice',
            unique_together={('device', 'device_uid')},
        ),
        migrations.AlterField(
            model_name='employeedevice',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_devices', to='core.employee'),
        ),
    ]
