# Generated by Django 5.2.12 on 2026-03-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_employeedevice_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedevice',
            name='user_name',
            field=models.CharField(blank=True, help_text='User name as stored on the device', max_length=100, null=True),
        ),
    ]
