# Generated by Django 5.2.12 on 2026-08-17 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_employeedevice_user_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='attlog_stamp',
            field=models.CharField(default='0', help_text='Resume point for attendance log uploads (ADMS)', max_length=32),
        ),
        migrations.AddField(
            model_name='device',
            name='device_info',
            field=models.TextField(blank=True, help_text='Raw INFO string last reported by the device', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Last contact from the device (any ADMS request)', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='operlog_stamp',
            field=models.CharField(default='0', help_text='Resume point for operation log uploads (ADMS)', max_length=32),
        ),
        migrations.AddField(
            model_name='device',
            name='push_enabled',
            field=models.BooleanField(default=False, help_text='Set automatically the first time this device contacts the ADMS endpoint.'),
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Device serial number (SN). Identifies the device when it pushes data to us.', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_sync_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField(help_text="Command body, e.g. 'CHECK' or 'DATA UPDATE USER PIN=1...'")),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent to device'), ('DONE', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('return_code', models.IntegerField(blank=True, help_text='Return value reported by the device (0 = success)', null=True)),
                ('response', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queued_device_commands', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='devices.device')),
            ],
            options={
                'verbose_name': 'Device Command',
                'verbose_name_plural': 'Device Commands',
                'db_table': 'device_commands',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'status'], name='device_comm_device__f1c307_idx')],
            },
        ),
    ]
