# Generated by Django 5.2.12 on 2026-08-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_device_attlog_stamp_device_device_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_id',
            field=models.CharField(blank=True, help_text="The terminal's own Device ID / machine number. Reported by the device; not unique between devices, so it is a label rather than an identity.", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_ip',
            field=models.CharField(blank=True, help_text="Source address of the device's most recent push. Informational.", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='mac_address',
            field=models.CharField(blank=True, help_text='Hardware MAC address, reported by the device after it connects. Useful for matching this record to a physical unit.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.CharField(blank=True, help_text='Address to connect to for pull-mode syncing. Leave empty for push-mode devices, which reach us and are identified by serial number.', max_length=50, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.CheckConstraint(condition=models.Q(('ip_address__isnull', False), ('serial_number__isnull', False), _connector='OR'), name='device_has_ip_or_serial'),
        ),
    ]
