# Generated by Django 5.2.12 on 2026-03-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_manage_devices', 'Can manage biometric devices'), ('can_manage_employees', 'Can manage employees'), ('can_approve_leaves', 'Can approve leave requests'), ('can_approve_travel_orders', 'Can approve travel orders')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
