# Generated by Django 5.2.12 on 2026-08-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='overtime_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pay rate per overtime hour. Leave empty if overtime is unpaid or rated elsewhere.', max_digits=10, null=True),
        ),
    ]
