"""
Django settings for ehajiri project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from django.contrib.messages import constants as message_constants

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-twm2ajx1fo7tgub!4p=dvy^j=r6*!5o&j#3c-*-3uhf-py%2!-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_celery_beat',
    'core',
    'devices',
    'attendance',
    'leaves',
    'travel_orders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ehajiri.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.navigation',
            ],
        },
    },
]

WSGI_APPLICATION = 'ehajiri.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Custom User Model
AUTH_USER_MODEL = 'core.User'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Static and Media
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Login URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# Map Django message levels onto Bootstrap alert classes. Without this, an
# error message renders as "alert-error", which Bootstrap does not define, so
# error messages appear unstyled.
MESSAGE_TAGS = {
    message_constants.DEBUG: 'secondary',
    message_constants.ERROR: 'danger',
}

# Attendance rules
# ----------------
# Weekly off days, using Python's weekday() numbering (Monday=0 ... Sunday=6).
# Saturday and Sunday.
#
# NOTE: the punches already in this database show a Sunday-Friday working week
# (Saturday: 4 punches on 4 dates; Sunday: 217 punches on 43 dates). If that is
# this office's actual pattern, set WEEKEND_DAYS = [5] for Saturday only,
# otherwise every Sunday worked is booked entirely as overtime.
WEEKEND_DAYS = [5, 6]

# Two scans closer together than this are the same person re-presenting a
# finger, not a check-in followed by a check-out.
MINIMUM_PUNCH_GAP_MINUTES = 5

# Overtime policy
OVERTIME_MINIMUM_MINUTES = 30   # ignore anything below this; avoids OT noise
OVERTIME_ROUNDING_MINUTES = 15  # round OT down to this increment
# Count overtime only for time worked after the shift ends. When False,
# overtime is any net worked time beyond the shift's scheduled hours.
OVERTIME_AFTER_SHIFT_END_ONLY = True
# Minimum net worked hours before a day counts as a full day rather than half.
HALF_DAY_MAX_HOURS = 4

# ADMS / WDMS push protocol
# -------------------------
# Devices post to /iclock/ instead of being polled over TCP. Configure the
# terminal with: Comm. -> Ethernet -> Cloud Server / ADMS -> this server's
# address and port.
# Auto-register unknown serial numbers as inactive devices awaiting approval.
# With this off, unknown devices are rejected outright.
ADMS_AUTO_REGISTER_DEVICES = True
# Roll pushed punches into daily summaries immediately, so the app works
# without a Celery worker running.
ADMS_PROCESS_ON_PUSH = True
# Maximum queued commands handed to a device in a single poll.
ADMS_MAX_COMMANDS_PER_POLL = 10
# A device is shown as offline if it has not contacted us within this window.
ADMS_OFFLINE_AFTER_SECONDS = 180

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {'format': '{asctime} {levelname} {name}: {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'standard'},
    },
    'loggers': {
        'devices': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'attendance': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
    },
}
