"""
Django settings for ehajiri project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.contrib.messages import constants as message_constants

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-twm2ajx1fo7tgub!4p=dvy^j=r6*!5o&j#3c-*-3uhf-py%2!-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# The public hostname this deployment serves. Everything host-dependent below
# is derived from it, so a new domain is a one-line change.
SITE_DOMAIN = os.environ.get('SITE_DOMAIN', 'attendance.thedeepit.com')

# Extra hostnames or IPs this deployment answers to, comma separated. Not
# needed for the biometric terminals, which reach the site over the internet on
# SITE_DOMAIN and so are already covered below; it exists for the case where
# something addresses this server by another name or by IP, which Django would
# otherwise reject with 400 DisallowedHost:
#     EXTRA_ALLOWED_HOSTS=attendance.lan,192.168.1.50
EXTRA_ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('EXTRA_ALLOWED_HOSTS', '').split(',')
    if host.strip()
]

# Hosts this site will answer to. Note that once this list is non-empty,
# Django enforces it even with DEBUG on, so the loopback IP is listed
# alongside 'localhost' to keep the dev server reachable either way.
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    SITE_DOMAIN,
    *EXTRA_ALLOWED_HOSTS,
]

# Origins allowed to submit forms. Django 4+ checks the Origin header on
# unsafe requests, and when nginx terminates TLS the browser sends
# https://... while Django sees a plain http request, so the https origin
# must be listed explicitly or every POST fails CSRF verification.
CSRF_TRUSTED_ORIGINS = [
    f'https://{SITE_DOMAIN}',
    f'http://{SITE_DOMAIN}',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_celery_beat',
    'core',
    'devices',
    'attendance',
    'leaves',
    'travel_orders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Must sit directly after SecurityMiddleware. Serves everything under
    # STATIC_ROOT with correct MIME types and cache headers, so static files
    # work whether traffic arrives via nginx, a tunnel, or gunicorn directly.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ehajiri.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.navigation',
            ],
        },
    },
]

WSGI_APPLICATION = 'ehajiri.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Custom User Model
AUTH_USER_MODEL = 'core.User'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Static and Media
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = 'static/'

# Source directory for this project's own assets (app.css, app.js).
STATICFILES_DIRS = [BASE_DIR / 'static']

# Destination for `manage.py collectstatic`: the directory the web server
# serves /static/ from. Override with the STATIC_ROOT environment variable on
# machines where that path does not exist, e.g. a Windows dev box.
STATIC_ROOT = Path(os.environ.get('STATIC_ROOT', f'/var/www/{SITE_DOMAIN}'))

# WhiteNoise storage: hashes filenames on collectstatic (app.4f2a1c9d.css) and
# pre-compresses them, which makes a one-year immutable cache safe because a
# changed file gets a new URL.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'core.storage.ResilientManifestStaticFilesStorage',
    },
}

# WhiteNoise serves static files only. User uploads (MEDIA_ROOT) still need
# nginx or a permission-checking Django view.
MEDIA_URL = 'media/'
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', BASE_DIR / 'media'))

# Employees created automatically from a device enrolment have no real email
# address. The placeholder uses our own domain so nothing is ever addressed to
# a third party's mail server; set it to a reserved domain such as
# 'invalid' if you would rather these never resemble deliverable addresses.
PLACEHOLDER_EMAIL_DOMAIN = os.environ.get('PLACEHOLDER_EMAIL_DOMAIN', SITE_DOMAIN)

# Login URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# Map Django message levels onto Bootstrap alert classes. Without this, an
# error message renders as "alert-error", which Bootstrap does not define, so
# error messages appear unstyled.
MESSAGE_TAGS = {
    message_constants.DEBUG: 'secondary',
    message_constants.ERROR: 'danger',
}

# Attendance rules
# ----------------
# Weekly off days, using Python's weekday() numbering (Monday=0 ... Sunday=6).
# Saturday and Sunday.
#
# NOTE: the punches already in this database show a Sunday-Friday working week
# (Saturday: 4 punches on 4 dates; Sunday: 217 punches on 43 dates). If that is
# this office's actual pattern, set WEEKEND_DAYS = [5] for Saturday only,
# otherwise every Sunday worked is booked entirely as overtime.
WEEKEND_DAYS = [5, 6]

# Two scans closer together than this are the same person re-presenting a
# finger, not a check-in followed by a check-out.
MINIMUM_PUNCH_GAP_MINUTES = 5

# Overtime policy
OVERTIME_MINIMUM_MINUTES = 30   # ignore anything below this; avoids OT noise
OVERTIME_ROUNDING_MINUTES = 15  # round OT down to this increment
# Count overtime only for time worked after the shift ends. When False,
# overtime is any net worked time beyond the shift's scheduled hours.
OVERTIME_AFTER_SHIFT_END_ONLY = True
# Minimum net worked hours before a day counts as a full day rather than half.
HALF_DAY_MAX_HOURS = 4

# ADMS / WDMS push protocol
# -------------------------
# Devices post to /iclock/ instead of being polled over TCP. Configure the
# terminal with: Comm. -> Ethernet -> Cloud Server / ADMS -> SITE_DOMAIN, port
# 80. The terminals are at remote sites and reach us over the internet, so
# /iclock/ is publicly exposed; see the deploy notes for what guards it.
# Auto-register unknown serial numbers as inactive devices awaiting approval.
# With this off, unknown devices are rejected outright - which is what a
# public /iclock/ wants once the real terminals are enrolled, since a serial
# number is the only credential the protocol has. Turn it off by setting
# ADMS_AUTO_REGISTER_DEVICES=0 in the service environment; no code change and
# no redeploy, so it can be flipped the moment enrolment finishes.
ADMS_AUTO_REGISTER_DEVICES = os.environ.get(
    'ADMS_AUTO_REGISTER_DEVICES', '1'
).lower() not in ('0', 'false', 'no')
# Roll pushed punches into daily summaries immediately, so the app works
# without a Celery worker running.
ADMS_PROCESS_ON_PUSH = True
# Maximum queued commands handed to a device in a single poll.
ADMS_MAX_COMMANDS_PER_POLL = 10
# A device is shown as offline if it has not contacted us within this window.
ADMS_OFFLINE_AFTER_SECONDS = 180

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {'format': '{asctime} {levelname} {name}: {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'standard'},
    },
    'loggers': {
        'devices': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'attendance': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
    },
}
