# Generated by Django 5.2.12 on 2026-08-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='accrued_days',
            field=models.DecimalField(decimal_places=1, default=0, help_text="Credited by this year's entitlement.", max_digits=6),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='lapsed_days',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Dropped because the balance hit its ceiling, or because the leave expires.', max_digits=6),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='opening_days',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Carried forward from the previous year.', max_digits=6),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='accrual',
            field=models.CharField(choices=[('YEARLY', 'Credited every year'), ('OCCASIONAL', 'Granted when the event happens')], default='YEARLY', help_text='Whether the entitlement arrives every year or only when the event occurs.', max_length=12),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='carry_forward',
            field=models.CharField(choices=[('NONE', 'Expires at the end of the year'), ('CAPPED', 'Accumulates up to a ceiling'), ('UNLIMITED', 'Accumulates without limit')], default='NONE', help_text='What happens to an unused balance when the year ends.', max_length=12),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='days_per_occurrence',
            field=models.IntegerField(blank=True, help_text='Days granted each time the event happens, e.g. 15 for death rituals. Only used by occasional leave.', null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_accumulation_days',
            field=models.IntegerField(blank=True, help_text='Ceiling on the accumulated balance, e.g. 180 for home leave. Leave empty when the accumulation is unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_occurrences_lifetime',
            field=models.IntegerField(blank=True, help_text='How many times this leave may be taken in a whole career, e.g. 2 for maternity. Leave empty for no limit.', null=True),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='remaining_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='total_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='used_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='days_per_year',
            field=models.IntegerField(default=0, help_text='Days credited each year. Only used by yearly leave.'),
        ),
    ]
