# Generated by Django 5.2.12 on 2026-03-29 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('core', '0001_initial'),
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_absences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='absence',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='core.employee'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='devices.device'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.employee'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendances', to='core.employee'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_attendances', to='core.shift'),
        ),
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together={('employee', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'device', 'timestamp', 'uid')},
        ),
        migrations.AlterUniqueTogether(
            name='dailyattendance',
            unique_together={('employee', 'date')},
        ),
    ]
