# Generated by Django 5.2.12 on 2026-08-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='punch_type',
            field=models.IntegerField(choices=[(0, 'Check In'), (1, 'Check Out'), (2, 'Break Out'), (3, 'Break In'), (4, 'Overtime In'), (5, 'Overtime Out')], default=0, help_text='0=Check in, 1=Check out, 2=Break out, 3=Break in, 4=Overtime in, 5=Overtime out'),
        ),
    ]
