# Generated by Django 5.2.12 on 2026-08-18 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_punch_type'),
        ('core', '0003_employee_overtime_hourly_rate'),
        ('devices', '0006_device_device_id_device_last_ip_device_mac_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='The working day this overtime belongs to.')),
                ('start_at', models.DateTimeField(help_text='When the overtime period began.')),
                ('end_at', models.DateTimeField(help_text='When it ended.')),
                ('hours', models.DecimalField(decimal_places=2, help_text='Payable overtime, after the minimum and rounding rules in settings.', max_digits=5)),
                ('job_performed', models.TextField(blank=True, help_text='What was worked on during this period. Appears on the overtime report; fill it in before approving.', null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Overtime rate applied to these hours. Copied from the employee when approved.', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Overtime Record',
                'verbose_name_plural': 'Overtime Records',
                'db_table': 'overtime_records',
                'ordering': ['-date', 'employee'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='reason',
            field=models.TextField(blank=True, help_text='Why this punch was entered by hand - forgotten scan, device outage, off-site work. Required for manual entries.', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='The administrator who entered this manually.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='source',
            field=models.CharField(choices=[('DEVICE', 'Biometric device'), ('MANUAL', 'Entered by administrator')], db_index=True, default='DEVICE', help_text='Where this punch came from.', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='device',
            field=models.ForeignKey(blank=True, help_text='The terminal that reported this punch. Empty for manual entries.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='uid',
            field=models.IntegerField(blank=True, help_text='Device UID', null=True),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source', 'MANUAL'), _negated=True), models.Q(('reason__isnull', False), models.Q(('reason', ''), _negated=True)), _connector='OR'), name='manual_attendance_requires_reason'),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_overtime_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_records', to='core.employee'),
        ),
        migrations.AddIndex(
            model_name='overtimerecord',
            index=models.Index(fields=['status', 'date'], name='overtime_re_status_f7e4e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='overtimerecord',
            unique_together={('employee', 'date')},
        ),
    ]
